<!DOCTYPE html><html lang="fr"><head><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="IE=edge"><meta name="viewport" content="width=device-width, initial-scale=1"><title></title><meta name="description"><!-- Favicon, Font Awesome & Google fonts--><link rel="icon" href="/images/pizza.png"><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"><link href="https://fonts.googleapis.com/css?family=Comfortaa:300,400,700" rel="stylesheet"><!-- Bootstrap & CSS--><link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"><link rel="stylesheet" type="text/css" href="/stylesheets/global_style.css"><link rel="stylesheet" type="text/css" href="/stylesheets/header_style.css"><link rel="stylesheet" type="text/css" href="/stylesheets/footer_style.css"><!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries--><!-- WARNING: Respond.js doesn't work if you view the page via file://--><!--if lt IE 9--><script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script><script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script></head><body><h1>Not Found</h1><h2>404</h2><pre>Error: Not Found
    at /home/wilder/hackaton/#2/wildcluedo/app.js:46:13
    at Layer.handle [as handle_request] (/home/wilder/hackaton/#2/wildcluedo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/wilder/hackaton/#2/wildcluedo/node_modules/express/lib/router/index.js:317:13)
    at /home/wilder/hackaton/#2/wildcluedo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/wilder/hackaton/#2/wildcluedo/node_modules/express/lib/router/index.js:335:12)
    at next (/home/wilder/hackaton/#2/wildcluedo/node_modules/express/lib/router/index.js:275:10)
    at /home/wilder/hackaton/#2/wildcluedo/node_modules/express/lib/router/index.js:635:15
    at next (/home/wilder/hackaton/#2/wildcluedo/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/home/wilder/hackaton/#2/wildcluedo/node_modules/express/lib/router/index.js:174:3)
    at router (/home/wilder/hackaton/#2/wildcluedo/node_modules/express/lib/router/index.js:47:12)</pre><!-- Appels JS--><script src="/javascripts/js.js"></script></body></html>